### ISSUE TITLE
Error with ENUM fields

### ISSUE THREAD

**Issue by emanuelet** [alirizwan/sequelize-graphql-schema#1]
In my sequelize schema I have a couple of enum fields (the database is Postgres).

If I don't exclude the corresponding models I receive this error:
```bash
Error: Schema must contain unique named types but contains multiple types named "UserroleEnumType".
    at invariant (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/jsutils/invariant.js:19:11)
    at typeMapReducer (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/type/schema.js:252:57)
    at typeMapReducer (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/type/schema.js:309:22)
    at typeMapReducer (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/type/schema.js:309:22)
    at Array.reduce (<anonymous>)
    at typeMapReducer (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/type/schema.js:280:38)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/emanuele/Projects/flightsuit_backend/node_modules/graphql/type/schema.js:125:28)
    at Object.<anonymous> (/home/emanuele/Projects/flightsuit_backend/app.js:227:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

Has someone encountered a similar issue?

**Comment by alirizwan** [comment]
I have not implemented proper ENUMS yet, for the primary reason they are not usually recommended but ENUMS should be converted into STRINGS instead of errors. If you could post your code example here for me to reproduce it would be easy to debug and resolve.

**Comment by emanuelet** [comment]
I pretty much have just implemented the library in the same way of the example.

On my **User** model this is the ENUM in question 

```js
role: {
      type: DataTypes.ENUM,
      values: ['guest', 'traveller', 'selfbooker', 'multibooker', 'admin']
    },
```

**Comment by alirizwan** [comment]
@emanuelet I've added it in my feature list, probably over the weekend I will do it.

**Comment by alirizwan** [comment]
@emanuelet it seems like a bug in graphql-sequelize library, [https://github.com/mickhansen/graphql-sequelize/blob/dbba02bdc8a30ad10464c1f7b39ae81976f614a9/src/attributeFields.js#L36](url)
It's supposed to cache enums but the cache is not working as expected resulting in above error. It took me a while to find the problem.

**Comment by alirizwan** [comment]
@emanuelet there was a bug in graphql-sequelize library where it caches enum types [https://github.com/mickhansen/graphql-sequelize/blob/dbba02bdc8a30ad10464c1f7b39ae81976f614a9/src/attributeFields.js#L36](url)

It took a while to find the problem, I guess I will create a PR there for the fix and link package with that PR until that's merged.

**Comment by alirizwan** [comment]
This is resolved in v0.1.47

**Comment by emanuelet** [comment]
awesome job @alirizwan. Only issue I found right now is that as you have ignored the `dist` folder, that has not been generated on the dedployment to npm. So when I did `npm install` I got `Error: Cannot find module './dist/sequelize-graphql-schema'`

**Comment by alirizwan** [comment]
I was going to configure Ci so ignore dist from git. You can run `npm run-script build` and you will get the dist folder back.

**Comment by emanuelet** [comment]
yeah I will do that, but at the same time I can do that only in development, Could you add the `build` script to the task that deploys the package to npm ?

**Comment by alirizwan** [comment]
Ci would build it before publishing, Ci is not configured yet sometime in this weekend I would do that. I have some other features on priority (bring more flexibility in remote schema and on demand remote schema stitching and response hooks being on top).
